# Essential Python for Data Analyst

- ✅ control flow + function
- ✅ OOP: Object Oriented Programming
- ✅ try except handle error
- ✅ context manager, csv, json
- ✅ API
- ✅ web scraping => static website is better
- intro to data science libraries

In [ ]:
## function def
def hello(name):
    print("Hi " + name)

In [ ]:
# lambda function => use to define function in one line
hello = lambda name: print("Hi " + name)

In [ ]:
hello("John")

Hi John


In [ ]:
# control flow
# if for while

In [ ]:
# if elif else
def grading(score):
    # docstring
    """
    this function return grade for a student in UK
    """
    if score >= 70:
        return "Distinction"
    elif score >= 60:
        return "Merit"
    elif score >= 50:
        return "Passed"
    else:
        return "Failed"

In [ ]:
grading(44)

'Failed'

In [ ]:
# return value from a function
def add_two_num(x,y):
    return x + y

result = add_two_num(10,15)
print(result)

25


In [ ]:
# for loop
nums = [1,2,3,4,5] ## => [2,4,6,8,10]

new_nums = [] # empty list

for num in nums:
    new_nums.append(num*2)

print(new_nums)

[2, 4, 6, 8, 10]


In [ ]:
# list comprehension => shorten the above code
nums = [1,2,3,4,5]

y = [num*2 for num in nums]

print(y)

[2, 4, 6, 8, 10]


In [ ]:
new_nums == y

True

In [ ]:
## program to check odd/ even numbers

nums = [35, 50, 22, 21, 28]

for num in nums:
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")

35 is odd
50 is even
22 is even
21 is odd
28 is even


In [ ]:
# while loop
count = 0

while count < 5: ## True
    print("hello")
    count += 1 # this line is very important

hello
hello
hello
hello
hello


In [ ]:
# get input from a user
# animal guessing game
def animal_guessing():
    set_animal = "hippo"
    answers = [] # empty list
    while True:
        guess = input("Guess the animal: ")
        answers.append(guess)
        if guess == set_animal:
            print("Hooray! correct answer")
            print(f"Logs: {answers}")
            break
        elif guess == "quit":
            print("See you next time.")
            break
        else:
            print("Nope! please try again.")

In [ ]:
animal_guessing()

Guess the animal: dog
Nope! please try again.
Guess the animal: cat
Nope! please try again.
Guess the animal: hippo
Hooray! correct answer
Logs: ['dog', 'cat', 'hippo']


In [ ]:
## HW01 - create game pao ying chub
import random

#count_win = 0
#count_lose = 0
#count_tie = 0

def paoyingchub():
    global count_win, count_lose, count_tie  # Declare variables as global
    count_win = 0
    count_lose = 0
    count_tie = 0
    choice = ["rock", "paper", "scissors"]
    print("This is PAO YING CHUB GAME !!!")
    answer = [] # blank
    while True:
        computer_pick = random.choice(choice)
        user_pick = input("Plese type: rock/paper/scissors (or 'quit' to exit): ")
        answer.append(user_pick)

        if computer_pick == user_pick:
            print("Tie.")
            count_tie += 1
        elif (computer_pick == "rock" and user_pick == "paper"):
            print("You win!")
            count_win += 1
        elif computer_pick == "rock" and user_pick == "scissors":
            print("You lose T^T")
            count_lose += 1
        elif computer_pick == "paper" and user_pick == "scissors":
            print("You win!")
            count_win += 1
        elif computer_pick == "paper" and user_pick == "rock":
            print("You lose T^T")
            count_lose += 1
        elif computer_pick == "scissors" and user_pick == "rock":
            print("You win!")
            count_win += 1
        elif computer_pick == "scissors" and user_pick == "paper":
            print("You lose T^T")
            count_lose += 1
        elif user_pick == "quit":
            print("See you next time.")
            answer.pop(-1)
            print(f"Log: {answer}")
            total_play = len(answer)
            print(f"Total played: {total_play}")
            print(f"Total win: {count_win}")
            print(f"Total lose: {count_lose}")
            print(f"Total tie: {count_tie}")
            break

In [ ]:
paoyingchub()

This is PAO YING CHUB GAME !!!
Plese type: rock/paper/scissors (or 'quit' to exit): rock
Tie.
Plese type: rock/paper/scissors (or 'quit' to exit): paper
Tie.
Plese type: rock/paper/scissors (or 'quit' to exit): scissors
You win!
Plese type: rock/paper/scissors (or 'quit' to exit): paper
You lose T^T
Plese type: rock/paper/scissors (or 'quit' to exit): paper
You win!
Plese type: rock/paper/scissors (or 'quit' to exit): paper
Tie.
Plese type: rock/paper/scissors (or 'quit' to exit): quit
See you next time.
Log: ['rock', 'paper', 'scissors', 'paper', 'paper', 'paper']
Total played: 6
Total win: 2
Total lose: 1
Total tie: 3


In [ ]:
## OOP => Object Oriented Programming

In [ ]:
## Dog
class Dog:
    # initialize
    def __init__(self, name, age, breed): # __ = dunder (double underscoll)
        self.name = name
        self.age = age
        self.breed = breed

    ## dog methods (functions)
    def sit(self):
        print("I'm  sitting now.")

    def sleep(self):
        print("I'm sleeping now.")

    def get_older(self, year):
        self.age += year

In [ ]:
dog1 = Dog("milo", 3, "chihuahua")

In [ ]:
dog1.get_older(3)
print(dog1.age)

6


In [ ]:
text = "a duck walks into a bar"

In [ ]:
## string method
text.split(" ")

['a', 'duck', 'walks', 'into', 'a', 'bar']

In [ ]:
"HELLO WORLD".lower()

'hello world'

In [ ]:
## list method
emp_list = []

emp_list.append("apple")
emp_list.append("banana")

emp_list

['apple', 'banana']

In [ ]:
class Apple:
    def __init__(self, size, price, color):
        self.size = size
        self.price = price
        self.color = color

In [ ]:
apple1 = Apple("medium", 5, "red")

In [ ]:
print(apple1.size, apple1.price, apple1.color)

medium 5 red


In [ ]:
## Python Class => OOP
## Class => attribute: name, age, breed
## Class => method: function => sit, sleep, get older

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

## Superclass
class Employee(Person):
    def __init__(self, name, company, position):
        super().__init__(name)
        self.name = name
        self.company = company
        self.position = position
    def greeting(self):
        print(f"Hi my name is {self.name} and I work for {self.company}")

In [ ]:
ps1 = Person("kang")
ps2 = Employee("john", "Google", "Data Analyst")

In [ ]:
ps1

In [ ]:
ps2

In [ ]:
ps2.greeting()

Hi my name is john and I work for Google


In [ ]:
ps1.greeting()

AttributeError: ignored

In [ ]:
## Superclass extend feature from base class

In [ ]:
## HW01 - pao ying chub game
## HW02 - class ATM at least 5 methods : balance, account name, account number, deposit, withdraw, OTP request, authenthication

class ATM:
    pass

In [ ]:
## try except block (traping the error with except)
try:
    print(dfgsdfgsdfg)
except ZeroDivisionError:
    print("Cannot divide by zero")
except NameError:
    print("Variable not found in our environment")
else:
    print("OK")
finally:
    print("End!")

Variable not found in our environment
End!


In [ ]:
## try except for syntax error
try:
    eval('print(1+5 ')
except:
    print("Syntax error")

Syntax error


In [ ]:
!pwd # Print Working Directory

/content


In [ ]:
!ls # list all file in Working Directory

friends.csv  sample_data


In [ ]:
!echo hello world # like print("Hello world")

hello world


In [ ]:
!cat friends.csv # Concatenate => review data in file ..

id,name,age,company
1,toy,30,Google
2,top,31,Amazon
3,jave,25,Microsoft
4,john,28,Meta
5,anna,29,Anaconda

In [ ]:
import csv

In [ ]:
# open csv file using read mode ("r")
file = open("friends.csv", "r")

In [ ]:
# read content in this file
data = csv.reader(file)

In [ ]:
data

In [ ]:
for row in data:
    print(row)

['id', 'name', 'age', 'company']
['1', 'toy', '30', 'Google']
['2', 'top', '31', 'Amazon']
['3', 'jave', '25', 'Microsoft']
['4', 'john', '28', 'Meta']
['5', 'anna', '29', 'Anaconda']


In [ ]:
# close file
file.close()

In [ ]:
# pandas
import pandas as pd
df = pd.read_csv("friends.csv")

# import csv
df = pd.read_csv("friends.csv")

# export csv
df.to_csv("haha.csv")

In [ ]:
df

id  name  age    company
0   1   toy   30     Google
1   2   top   31     Amazon
2   3  jave   25  Microsoft
3   4  john   28       Meta
4   5  anna   29   Anaconda

In [ ]:
!cat haha.csv

,id,name,age,company
0,1,toy,30,Google
1,2,top,31,Amazon
2,3,jave,25,Microsoft
3,4,john,28,Meta
4,5,anna,29,Anaconda


In [ ]:
## context manager => with ; open and close file for user automatically
        # sometime if user forget to close the file after open and get data, the file will broken
## use to open data file

In [ ]:
# import csv
from csv import reader
result = []

with open("friends.csv", "r") as file:
    data = reader(file)
    for row in data:
        result.append(row)

result

[['id', 'name', 'age', 'company'],
 ['1', 'toy', '30', 'Google'],
 ['2', 'top', '31', 'Amazon'],
 ['3', 'jave', '25', 'Microsoft'],
 ['4', 'john', '28', 'Meta'],
 ['5', 'anna', '29', 'Anaconda']]

In [ ]:
print(type(result))

<class 'list'>


In [ ]:
## write mode
import csv

header = ["id", "course", "students"]
body_data = [
    [1, "data science", 30],
    [2, "marketing", 28],
    [3, "power BI", 35]
]

with open("courses.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(body_data)

In [ ]:
!ls

courses.csv  friends.csv  haha.csv  sample_data


In [ ]:
!cat courses.csv

id,course,students
1,data science,30
2,marketing,28
3,power BI,35


In [ ]:
!cat customer.json

{
    "name": "toy",
    "age": 35,
    "company": "DataRockie",
    "movie_lover": true,
    "movies": ["Dark Knight", "Superman"]
}

In [ ]:
import json

with open("customer.json", "r") as file:
    customer = json.load(file)
print(customer, type(customer))

{'name': 'toy', 'age': 35, 'company': 'DataRockie', 'movie_lover': True, 'movies': ['Dark Knight', 'Superman']} <class 'dict'>


In [ ]:
## dict => json
import json #.load() , .dump()
book = {
    "name": "How to be better at almost everything",
    "year": 2018,
    "author": "Pat Flynn",
    "favorite": True
}

with open("book.json", "w") as file:
    json.dump(book, file)
    print("Create file successfully!")


Create file successfully!


In [ ]:
!cat book.json

{"name": "How to be better at almost everything", "year": 2018, "author": "Pat Flynn", "favorite": true}

In [ ]:
import json
with open("book.json", "r") as file:
    book = json.load(file)
print(book, type(book))

{'name': 'How to be better at almost everything', 'year': 2018, 'author': 'Pat Flynn', 'favorite': True} <class 'dict'>


In [ ]:
!cat courses.csv

id,course,students
1,data science,30
2,marketing,28
3,power BI,35


In [ ]:
try:
    with open("COURSES.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
         print(row)
except FileNotFoundError:
    print("Please check file name again.")
else:
    print("Open file successfully.")

Please check file name again.


In [ ]:
# API => Application Programming Interface
# Communication two machines

# request-reponse cycle
from requests import get

url = "https://swapi.dev/api/people/1"

resp = get(url)

## if success, OK 200
resp.status_code

## see information
resp.json()["name"]


'Luke Skywalker'

In [ ]:
resp.json()

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.dev/api/planets/1/',
 'films': ['https://swapi.dev/api/films/1/',
  'https://swapi.dev/api/films/2/',
  'https://swapi.dev/api/films/3/',
  'https://swapi.dev/api/films/6/'],
 'species': [],
 'vehicles': ['https://swapi.dev/api/vehicles/14/',
  'https://swapi.dev/api/vehicles/30/'],
 'starships': ['https://swapi.dev/api/starships/12/',
  'https://swapi.dev/api/starships/22/'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.dev/api/people/1/'}

In [ ]:
import requests
import time

characters = []

for i in range(5):
    url = f"https://swapi.dev/api/people/{i+1}"
    resp = requests.get(url)
    if resp.status_code == 200:
        json_data = resp.json()
        characters.append(
            (json_data["name"],
            json_data["height"])
        )
    else:
        characters.append("error")

    # break a second
    time.sleep(1)

print(characters)

[('Luke Skywalker', '172'), ('C-3PO', '167'), ('R2-D2', '96'), ('Darth Vader', '202'), ('Leia Organa', '150')]


In [ ]:
import requests
import time

characters = []
total_characters = 5  # Assuming there are 10 characters in the SWAPI

for i in range(1, total_characters + 1):
    url = f"https://swapi.dev/api/people/{i}"
    resp = requests.get(url)

    if resp.status_code == 200:
        json_data = resp.json()
        characters.append(
            (json_data["name"], json_data["height"])
        )
    else:
        characters.append("error")

    # break for a second
    time.sleep(1)

print(characters)

[('Luke Skywalker', '172'), ('C-3PO', '167'), ('R2-D2', '96'), ('Darth Vader', '202'), ('Leia Organa', '150')]


In [ ]:
url = f"https://swapi.dev/api/people/{i+1}"
print(url)

https://swapi.dev/api/people/6


In [ ]:
## HW03 - find public API and use Python to get data

In [ ]:
# GET languages
import requests

url = "https://google-translate1.p.rapidapi.com/language/translate/v2/languages"

headers = {
	"Accept-Encoding": "application/gzip",
	"X-RapidAPI-Key": "65eaabd2cemsh237a67663c12886p1e47ffjsn964e80054059",
	"X-RapidAPI-Host": "google-translate1.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())



# POST detect
import requests

url = "https://google-translate1.p.rapidapi.com/language/translate/v2/detect"

payload = { "q": "สวัสดีชาวโลก!" }
headers = {
	"content-type": "application/x-www-form-urlencoded",
	"Accept-Encoding": "application/gzip",
	"X-RapidAPI-Key": "65eaabd2cemsh237a67663c12886p1e47ffjsn964e80054059",
	"X-RapidAPI-Host": "google-translate1.p.rapidapi.com"
}

response = requests.post(url, data=payload, headers=headers)

print(response.json())




# POST translate
import requests

url = "https://google-translate1.p.rapidapi.com/language/translate/v2"

payload = {
	"q": "Hello, world!",
	"target": "es",
	"source": "en"
}
headers = {
	"content-type": "application/x-www-form-urlencoded",
	"Accept-Encoding": "application/gzip",
	"X-RapidAPI-Key": "65eaabd2cemsh237a67663c12886p1e47ffjsn964e80054059",
	"X-RapidAPI-Host": "google-translate1.p.rapidapi.com"
}

response = requests.post(url, data=payload, headers=headers)

print(response.json())

{'message': 'You have exceeded the MONTHLY quota for Characters on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/googlecloud/api/google-translate1'}
{'message': 'You have exceeded the MONTHLY quota for Characters on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/googlecloud/api/google-translate1'}
{'message': 'You have exceeded the MONTHLY quota for Characters on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/googlecloud/api/google-translate1'}


In [ ]:
# web scraping
# install new library on google colab
# pip => package manager in Python

!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=5dd8780aae48fdd829a81b77ba0ae8b2da43bd4e42e6992946fc2fbeef73668c
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list | grep "gaz"

gazpacho                         1.1


In [ ]:
## import function
from gazpacho import Soup
import requests

In [ ]:
## web scraping basics (ดึงข้อมูลจากหน้าเว็บ)

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}

html = requests.get(url, headers=headers) ## Accept-Language: en

In [ ]:
html

<Response [200]>

In [ ]:
imdb = Soup(html.text)

In [ ]:
titles = imdb.find("h3", {"class": "lister-item-header"})

In [ ]:
titles = imdb.find("h3", {"class": "lister-item-header"})

#clean_titles = []

#for title in titles:
#    clean_titles.append(title.strip())

## list comprehension

clean_titles =  [title.strip() for title in titles]

TypeError: ignored

In [ ]:
titles[0].strip() # .strip will keep only text element (delete html element)

'1. The Shawshank Redemption (1994)'

In [ ]:
clean_titles

['1. The Shawshank Redemption (1994)',
 '2. The Godfather (1972)',
 '3. The Dark Knight (2008)',
 "4. Schindler's List (1993)",
 '5. The Lord of the Rings: The Return of the King (2003)',
 '6. The Godfather Part II (1974)',
 '7. 12 Angry Men (1957)',
 '8. Pulp Fiction (1994)',
 '9. Fight Club (1999)',
 '10. The Lord of the Rings: The Fellowship of the Ring (2001)',
 '11. Inception (2010)',
 '12. Forrest Gump (1994)',
 '13. The Lord of the Rings: The Two Towers (2002)',
 '14. The Good, the Bad and the Ugly (1966)',
 '15. Spider-Man: Across the Spider-Verse (2023)',
 '16. Interstellar (2014)',
 '17. Goodfellas (1990)',
 '18. The Matrix (1999)',
 "19. One Flew Over the Cuckoo's Nest (1975)",
 '20. Star Wars: Episode V - The Empire Strikes Back (1980)',
 '21. The Silence of the Lambs (1991)',
 '22. Se7en (1995)',
 '23. Spirited Away (2001)',
 '24. Saving Private Ryan (1998)',
 '25. The Green Mile (1999)',
 '26. Star Wars: Episode IV - A New Hope (1977)',
 '27. City of God (2002)',
 '28. Te

In [ ]:
 ## get rating from the website
 ## div: ratings-imdb-rating

ratings = imdb.find("div", {"class": "ratings-imdb-rating"})

clean_ratings = [float(rating.strip()) for rating in ratings]

clean_ratings

[9.3,
 9.2,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 8.9,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.7,
 8.7,
 8.7,
 8.7,
 8.7,
 8.7,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5]

In [ ]:
import pandas as pd

# create dataframe
movie_database = pd.DataFrame(data = {
    "title": clean_titles,
    "rating": clean_ratings
})

# print first five rows
movie_database.head()


title  rating
0                 1. The Shawshank Redemption (1994)     9.3
1                            2. The Godfather (1972)     9.2
2                          3. The Dark Knight (2008)     9.0
3                         4. Schindler's List (1993)     9.0
4  5. The Lord of the Rings: The Return of the Ki...     9.0

In [ ]:
 ## HW04 - Create Lauched Year column in a dataframe
 movie_data["yaer"]

NameError: ignored

# **Intro to Data Science Libraries**

- numpy
- pandas
- sklearn (machine learning)
- statsmodel (statistics)

In [ ]:
# numerical python
# very fast
import numpy as np

In [ ]:
import numpy as pd

nums = [1,2,3,4,5]

In [ ]:
[num*2 for num in nums]

[2, 4, 6, 8, 10]

In [ ]:
nums = np.array(nums)

In [ ]:
type(nums)

numpy.ndarray

In [ ]:
nums /5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# STATISTICS CALCULATION
np.median(nums)

3.0

In [ ]:
nums.sum()

15

In [ ]:
np.sum(nums)

15

In [ ]:
np.arange(10)  # range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10) +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0, 10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
## 2D array
n2 = np.array([
    [1,2],
    [3,4]
])


In [ ]:
print(n2, type(n2))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
## matrix * matrix
## .dot notation

In [ ]:
m1 = np.array([[1,2],[5,5]])
m2 = np.array([[4,2],[1,2]])

In [ ]:
np.dot(m1,m2)

array([[ 6,  6],
       [25, 20]])

In [ ]:
# import pandas
# manage dataframe
import pandas as pd

In [ ]:
# read data from csv file
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [ ]:
type(mtcars)

pandas.core.frame.DataFrame

In [ ]:
mtcars.shape

(32, 12)

In [ ]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
df = mtcars[ ["mpg", "model", "hp"] ].tail(3)

In [ ]:
df

mpg          model   hp
29  19.7   Ferrari Dino  175
30  15.0  Maserati Bora  335
31  21.4     Volvo 142E  109

In [ ]:
df["mpg_double"] = df["mpg"] * 2

In [ ]:
df

mpg          model   hp  mpg_double
29  19.7   Ferrari Dino  175        39.4
30  15.0  Maserati Bora  335        30.0
31  21.4     Volvo 142E  109        42.8

In [ ]:
df["mpg"].mean()

18.7

In [ ]:
np.mean(df["mpg"])

18.7

In [ ]:
df["mpg"].mean()

18.7

In [ ]:
colnames = list(df.columns)
colnames[0] = "New Model"
print(colnames)

df.columns = colnames

['New Model', 'model', 'hp', 'mpg_double']


In [ ]:
df.head()

New Model          model   hp  mpg_double
29       19.7   Ferrari Dino  175        39.4
30       15.0  Maserati Bora  335        30.0
31       21.4     Volvo 142E  109        42.8

In [ ]:
mtcars["mpg"] > 30

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29    False
30    False
31    False
Name: mpg, dtype: bool

In [ ]:
# filter traditional
mtcars[ (mtcars["mpg"] > 30) & (mtcars["hp"] > 100)]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# pandas .query()
# condition used to filter dataframe
mtcars.query(" mpg > 30 and hp > 100 ")

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# aggregate + group by
# read data

import pandas as pd
store = pd.read_csv("store.csv")

In [ ]:
col_names = list(store.columns)

col_names

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [ ]:
clean_col_names = [col.lower().replace(" ", "_").replace("-", "_") for col in col_names]

# clean column names
store.columns = clean_col_names

In [ ]:
store.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [ ]:
 store

In [ ]:
store["sales"].sum()

3530365.2627

In [ ]:
result = store.groupby(["segment","category"])["sales"].sum().reset_index()

In [ ]:
result

segment         category        sales
0     Consumer        Furniture  602933.1191
1     Consumer  Office Supplies  559890.1170
2     Consumer       Technology  620898.9760
3    Corporate        Furniture  363047.5441
4    Corporate  Office Supplies  363821.3630
5    Corporate       Technology  379204.6220
6  Home Office        Furniture  187444.2375
7  Home Office  Office Supplies  187860.2730
8  Home Office       Technology  265265.0110

In [ ]:
# aggregate
store.groupby("segment")["sales"].\ # backslash is for new row.
    agg(["sum", "mean", "std"]).\
    reset_index()

segment           sum        mean         std
0     Consumer  1.783722e+06  224.254741  592.635923
1    Corporate  1.106074e+06  233.743349  613.972522
2  Home Office  6.405695e+05  235.071384  677.872007
3      Storage  0.000000e+00         NaN         NaN

In [ ]:
## R version
## store %>% groupby(segment) %>% summarise(sum(sales))

In [ ]:
result.to_csv("agg_data.csv")

In [ ]:
## read data from sql database
## chinook.db

import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

df = pd.read_sql("SELECT * FROM customers WHERE country = 'USA'", con)

## close connect
con.close()


In [ ]:
df.head()

CustomerId FirstName LastName                Company  \
0          16     Frank   Harris            Google Inc.   
1          17      Jack    Smith  Microsoft Corporation   
2          18  Michelle   Brooks                   None   
3          19       Tim    Goyer             Apple Inc.   
4          20       Dan   Miller                   None   

                     Address           City State Country  PostalCode  \
0  1600 Amphitheatre Parkway  Mountain View    CA     USA  94043-1351   
1            1 Microsoft Way        Redmond    WA     USA  98052-8300   
2               627 Broadway       New York    NY     USA  10012-2612   
3            1 Infinite Loop      Cupertino    CA     USA       95014   
4       541 Del Medio Avenue  Mountain View    CA     USA   94040-111   

               Phone                Fax                    Email  SupportRepId  
0  +1 (650) 253-0000  +1 (650) 253-0000       fharris@google.com             4  
1  +1 (425) 882-8080  +1 (425) 882-8081  jacksmith@microsoft.com             5  
2  +1 (212) 221-3546  +1 (212) 221-4679        michelleb@aol.com             3  
3  +1 (408) 996-1010  +1 (408) 996-1011         tgoyer@apple.com             3  
4  +1 (650) 644-3358               None      dmiller@comcast.com             4

In [ ]:
df[ df.State == "WA" ]

CustomerId FirstName LastName                Company          Address  \
1          17      Jack    Smith  Microsoft Corporation  1 Microsoft Way   

      City State Country  PostalCode              Phone                Fax  \
1  Redmond    WA     USA  98052-8300  +1 (425) 882-8080  +1 (425) 882-8081   

                     Email  SupportRepId  
1  jacksmith@microsoft.com             5

In [ ]:
df[ df["State"] == "WA" ]

CustomerId FirstName LastName                Company          Address  \
1          17      Jack    Smith  Microsoft Corporation  1 Microsoft Way   

      City State Country  PostalCode              Phone                Fax  \
1  Redmond    WA     USA  98052-8300  +1 (425) 882-8080  +1 (425) 882-8081   

                     Email  SupportRepId  
1  jacksmith@microsoft.com             5

In [ ]:
import pandas as pd

In [ ]:
# sklearn basics
# ref:

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

# read data
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")
mtcars.head()

# prepare data
X = mtcars.drop(["model", "mpg"], axis=1) # axis=1 is column , axis=0 is row
y = mtcars["mpg"]

# split data
# set.seed(42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# train model
model = BaggingRegressor()
model.fit(X_train, y_train)

# prediction
p = model.predict(X_test)

# R squared
model.score(X_test, y_test)

# MAE mean absolute error
# mean(abs(y_test - p))
np.mean(np.abs(y_test - p))

# MSE mean square error
np.mean((y_test - p)**2)


6.207037500000002

In [ ]:
# save model
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)